2020-04-06 20:37:32,985 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2020-04-06 20:37:33,096 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2020-04-06 20:37:38,860 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2020-04-06 20:37:39,447 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2020-04-06 20:37:39,471 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2020-04-06 20:37:40,110 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-04-06 20:37:47,169 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'RatingsAndReviewsAPI', 'review_stats']'
2020-04-06 20:37:47,176 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 20:37:56,452 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'available_apps', '{"lang": "en", "series": "trusty", "arch": "amd64"}']'
2020-04-06 20:37:56,453 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 20:37:56,454 - softwarecenter.db.update - WARNING - update_from_software_center_agent: error: 'WARNING:__main__:no data\n'
2020-04-06 20:37:57,078 - softwarecenter.db.utils - INFO - software-center-agent finished with status 1
2020-04-06 20:37:57,080 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'exhibits', '{"lang": "en", "series": "trusty"}']'
2020-04-06 20:37:57,080 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 20:38:32,225 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2020-04-06 20:46:07,677 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "ukopp"}']'
2020-04-06 20:46:07,679 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 20:46:07,690 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:no data

2020-04-06 20:46:07,705 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:no data

2020-04-06 21:39:59,153 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-04-06 22:03:41,996 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "clips"}']'
2020-04-06 22:03:42,008 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 22:03:42,012 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:no data

2020-04-06 22:03:42,013 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:no data

2020-04-06 22:22:45,603 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "git"}']'
2020-04-06 22:22:45,604 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 22:22:45,608 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:no data

2020-04-06 22:22:45,608 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:no data

2020-04-06 23:05:41,918 - softwarecenter.backend - WARNING - _on_trans_error: 'TransactionFailed(u'error-cache-broken:  The following packages have unmet dependencies:\n\nevince: Depends: libevdocument3-4 (= 3.18.2-1ubuntu4.6) but 3.10.3-0ubuntu10.4 is installed\n        Depends: libevview3-3 (= 3.18.2-1ubuntu4.6) but 3.10.3-0ubuntu10.4 is installed\ngstreamer1.0-clutter: Depends: libc6 (>= 2.14) but 2.23-0ubuntu11 is installed\n                      Depends: libcogl15 (>= 1.15.8) but it is not installed\n                      Depends: libglib2.0-0 (>= 2.37.3) but 2.48.2-0ubuntu4.6 is installed\n',)' '<AptTransaction object at 0x7fabbbe75370 (aptdaemon+client+AptTransaction at 0x1dd1e00)>' 'xclip'
2020-04-06 23:05:49,200 - softwarecenter.backend - ERROR - error in _on_trans_finished 'Error: The package system is broken
Check if you are using third party repositories. If so disable them, since they are a common source of problems.
Furthermore run the following command in a Terminal: apt-get install -f

The following packages have unmet dependencies:

evince: Depends: libevdocument3-4 (= 3.18.2-1ubuntu4.6) but 3.10.3-0ubuntu10.4 is installed
        Depends: libevview3-3 (= 3.18.2-1ubuntu4.6) but 3.10.3-0ubuntu10.4 is installed
gstreamer1.0-clutter: Depends: libc6 (>= 2.14) but 2.23-0ubuntu11 is installed
                      Depends: libcogl15 (>= 1.15.8) but it is not installed
                      Depends: libglib2.0-0 (>= 2.37.3) but 2.48.2-0ubuntu4.6 is installed
'
2020-04-06 23:07:25,663 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-04-06 23:08:39,005 - softwarecenter.backend - WARNING - _on_trans_error: 'NotAuthorizedError(u"('system-bus-name', {'name':  ':1.75'}): org.debian.apt.install-or-remove-packages",)' '<AptTransaction object at 0x7fabbbe354b0 (aptdaemon+client+AptTransaction at 0x319b740)>' 'xclip'
2020-04-06 23:08:39,072 - softwarecenter.backend - ERROR - error in _on_trans_finished 'Error: You are not allowed to perform this action
You don't have the required privileges to perform this action.

org.freedesktop.PolicyKit.Error.NotAuthorized: ('system-bus-name', {'name': ':1.75'}): org.debian.apt.install-or-remove-packages'
2020-04-06 23:08:57,498 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-04-06 23:09:37,669 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "xclip"}']'
2020-04-06 23:09:37,674 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2020-04-06 23:09:37,675 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:no data

2020-04-06 23:09:37,676 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:no data

2020-04-06 23:10:05,091 - softwarecenter.backend - WARNING - _on_trans_error: 'NotAuthorizedError(u"('system-bus-name', {'name':  ':1.75'}): org.debian.apt.install-or-remove-packages",)' '<AptTransaction object at 0x7fabcdfd7320 (aptdaemon+client+AptTransaction at 0x2e1ff80)>' 'xclip'
2020-04-06 23:10:05,178 - softwarecenter.backend - ERROR - error in _on_trans_finished 'Error: You are not allowed to perform this action
You don't have the required privileges to perform this action.

org.freedesktop.PolicyKit.Error.NotAuthorized: ('system-bus-name', {'name': ':1.75'}): org.debian.apt.install-or-remove-packages'
2020-04-06 23:10:16,297 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2020-04-07 00:03:55,156 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
